
# config/snippets.yaml
listen_lora:
  enable: true
  r: 8
  alpha: 16
  dropout: 0.05
  layers: 12
  target_modules: ["q_proj","k_proj","v_proj","o_proj"]
train:
  first_token_ce_weight: 12.0
  kd_first_k_weight: 2.0
  kd_tau: 2.0
  rehearsal_text_frac: 0.25
