
# config/snippets.yaml
multi_depth_adapters:
  enable: true
  d_z: 256
  layers: [5, 10, 15]
  n_heads: 8
  dropout: 0.1
train:
  first_token_ce_weight: 10.0
  kd_first_k_weight: 1.0
  kd_tau: 2.0
logging:
  log_adapter_alpha: true
