# Test config for Stage 0 (CoT baseline)
# Modified for MacBook / single GPU / faster iteration

project: coconut
save_path: ../runs/stage0
name: gsm-cot-test

only_eval: False

coconut: False
cot: True
no_thoughts: False
no_cot: False

c_thought: 0
epochs_per_stage: 1
max_latent_stage: 0
pad_latent_to_max: True

save_only_improve: True
uniform_prob: 0.0
model_id: openai-community/gpt2
load_model_path: None
seed: 0
resume: 0
bf16: False
train_path: data/gsm_train.json
val_path: data/gsm_valid.json
reset_optimizer: False

# Reduced for MacBook / faster iteration
batch_size_training: 8
gradient_accumulation_steps: 4  # Effective batch = 8*4 = 32
num_epochs: 3  # Instead of 25 for quick test
debug: True  # Set to True to skip wandb

lr: !!float "1e-4"
weight_decay: 0.01
