#!/usr/bin/env bash
set -euo pipefail

# run_llama_hero_smoke.sh
# Minimal checkpoints/resume drill for the hero pipeline.
# Runs a tiny Stage A/B with per-epoch checkpointing into runs/hero-smoke.

RUN_TAG="hero_smoke"
TRAIN_SAMPLES_STAGEA=${TRAIN_SAMPLES_STAGEA:-96}
TRAIN_SAMPLES_STAGEB=${TRAIN_SAMPLES_STAGEB:-192}
EPOCHS_STAGEA=${EPOCHS_STAGEA:-1}
EPOCHS_STAGEB=${EPOCHS_STAGEB:-1}
BATCH_SIZE_STAGEA=${BATCH_SIZE_STAGEA:-8}
BATCH_SIZE_STAGEB=${BATCH_SIZE_STAGEB:-16}
SAVE_EVERY_STAGEA=${SAVE_EVERY_STAGEA:-1}
SAVE_EVERY_STAGEB=${SAVE_EVERY_STAGEB:-1}
SAMPLES=${SAMPLES:-20}

RUN_TAG="$RUN_TAG" \
TRAIN_SAMPLES_STAGEA=$TRAIN_SAMPLES_STAGEA \
TRAIN_SAMPLES_STAGEB=$TRAIN_SAMPLES_STAGEB \
EPOCHS_STAGEA=$EPOCHS_STAGEA \
EPOCHS_STAGEB=$EPOCHS_STAGEB \
BATCH_SIZE_STAGEA=$BATCH_SIZE_STAGEA \
BATCH_SIZE_STAGEB=$BATCH_SIZE_STAGEB \
SAVE_EVERY_STAGEA=$SAVE_EVERY_STAGEA \
SAVE_EVERY_STAGEB=$SAVE_EVERY_STAGEB \
SAMPLES=$SAMPLES \
  bash "$(dirname "$0")/run_llama_single.sh" --hero "$@"
